version: '3.8'

services:

  db:
    image: postgres:13.12
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  product-api:
    build: ./ProductMS
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db

  warehouse-api:
    build: ./WarehouseMS
    ports:
      - "8001:8001"  # Cambia el puerto externo para evitar conflictos
    depends_on:
      - db
      - product-api
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db

  inventory-api:
    build: ./InventoryMS
    ports:
      - "8002:8002"  # Cambia el puerto externo para evitar conflictos
    depends_on:
      - db
      - warehouse-api
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db

  integration-api:
    build: ./IntegrationMS
    ports:
      - "8003:8003"  # Cambia el puerto externo para evitar conflictos
    depends_on:
      - db
      - inventory-api
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    container_name: frontend-dev
    depends_on:
      - db

  sale-api:
    build: ./SaleMS
    ports:
      - "8004:8004"  # Cambia el puerto externo para evitar conflictos
    depends_on:
      - db
      - integration-api
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  esdata: