apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-api
  template:
    metadata:
      labels:
        app: integration-api
    spec:
      containers:
      - name: integration-api
        image: jorgepdlr/iaps_v2:v2_iaspproject-integration-api
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          value: "postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db"
---
apiVersion: v1
kind: Service
metadata:
  name: integration-api-service
spec:
  selector:
    app: integration-api
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
