apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: inventory-api
        image: jorgepdlr/iaps_v2:v2_iaspproject-inventory-api
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          value: "postgresql://fastapi_user:fastapi_password@db:5432/fastapi_db"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-api-service
spec:
  selector:
    app: inventory-api
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: NodePort
