apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.12
        env:
        - name: POSTGRES_USER
          value: fastapi_user
        - name: POSTGRES_PASSWORD
          value: fastapi_password
        - name: POSTGRES_DB
          value: fastapi_db
        ports:
        - containerPort: 5432